import numpy as np
import cv2 as cv
from opticalFlow import opticalFlow
from reduce import reduce 
from expand import expand
from warp import warp
from HLK import HLK
import itertools
from matplotlib import pyplot as plt

baseImage = cv.imread("./input/TestSeq/Shift0.png",0)
newImage = cv.imread("./input/TestSeq/ShiftR2.png",0)
baseImage = cv.GaussianBlur(baseImage,(5,5),1)
newImage = cv.GaussianBlur(newImage,(5,5),1)
U, V = opticalFlow(baseImage,newImage)
im_u = cv.applyColorMap(U.astype(np.uint8), cv.COLORMAP_JET)
im_v = cv.applyColorMap(V.astype(np.uint8), cv.COLORMAP_JET)
plt.figure(1)
plt.subplot(121)
plt.subplot(121).set_title("Shift in X")
plt.imshow(im_u)
plt.subplot(122)
plt.subplot(122).set_title("Shift in Y")
plt.imshow(im_v)
plt.show()
baseImage = cv.imread("./input/TestSeq/Shift0.png",0)
newImage = cv.imread("./input/TestSeq/ShiftR5U5.png",0)
baseImage = cv.GaussianBlur(baseImage,(5,5),1)
newImage = cv.GaussianBlur(newImage,(5,5),1)
U, V = opticalFlow(baseImage,newImage)
im_u = cv.applyColorMap(U.astype(np.uint8), cv.COLORMAP_JET)
im_v = cv.applyColorMap(V.astype(np.uint8), cv.COLORMAP_JET)
plt.figure(1)
plt.subplot(121)
plt.subplot(121).set_title("Shift in X")
plt.imshow(im_u)
plt.subplot(122)
plt.subplot(122).set_title("Shift in Y")
plt.imshow(im_v)
plt.show()
baseImage = cv.imread("./input/TestSeq/Shift0.png",0)
newImage = cv.imread("./input/TestSeq/ShiftR10.png",0)
baseImage = cv.GaussianBlur(baseImage,(5,5),1)
newImage = cv.GaussianBlur(newImage,(5,5),1)
U, V = opticalFlow(baseImage,newImage)
im_u = cv.applyColorMap(U.astype(np.uint8), cv.COLORMAP_JET)
im_v = cv.applyColorMap(V.astype(np.uint8), cv.COLORMAP_JET)
plt.figure(1)
plt.subplot(121)
plt.subplot(121).set_title("Shift in X")
plt.imshow(im_u)
plt.subplot(122)
plt.subplot(122).set_title("Shift in Y")
plt.imshow(im_v)
plt.show()
baseImage = cv.imread("./input/TestSeq/Shift0.png",0)
newImage = cv.imread("./input/TestSeq/ShiftR20.png",0)
baseImage = cv.GaussianBlur(baseImage,(5,5),1)
newImage = cv.GaussianBlur(newImage,(5,5),1)
U, V = opticalFlow(baseImage,newImage)
im_u = cv.applyColorMap(U.astype(np.uint8), cv.COLORMAP_JET)
im_v = cv.applyColorMap(V.astype(np.uint8), cv.COLORMAP_JET)
plt.figure(1)
plt.subplot(121)
plt.subplot(121).set_title("Shift in X")
plt.imshow(im_u)
plt.subplot(122)
plt.subplot(122).set_title("Shift in Y")
plt.imshow(im_v)
plt.show()
baseImage = cv.imread("./input/TestSeq/Shift0.png",0)
newImage = cv.imread("./input/TestSeq/ShiftR40.png",0)
baseImage = cv.GaussianBlur(baseImage,(5,5),1)
newImage = cv.GaussianBlur(newImage,(5,5),1)
U, V = opticalFlow(baseImage,newImage)
im_u = cv.applyColorMap(U.astype(np.uint8), cv.COLORMAP_JET)
im_v = cv.applyColorMap(V.astype(np.uint8), cv.COLORMAP_JET)
plt.figure(1)
plt.subplot(121)
plt.subplot(121).set_title("Shift in X")
plt.imshow(im_u)
plt.subplot(122)
plt.subplot(122).set_title("Shift in Y")
plt.imshow(im_v)
plt.show()
DataSeq1_1 = cv.imread("./input/DataSeq1/yos_img_01.jpg",0)
red0, red1, red2, red3 = reduce(DataSeq1_1)
fig, axs = plt.subplots(2,2)
axs[0,0].imshow(red0,cmap='gray')
axs[0,1].imshow(red1,cmap='gray')
axs[1,0].imshow(red2,cmap='gray')
axs[1,1].imshow(red3,cmap='gray')
plt.show()
g3, lap1, lap2, lap3 = expand(DataSeq1_1)
fig, axs = plt.subplots(2,2)
axs[0,0].imshow(g3,cmap='gray')
axs[0,1].imshow(lap1,cmap='gray')
axs[1,0].imshow(lap2,cmap='gray')
axs[1,1].imshow(lap3,cmap='gray')
plt.show()
DataSeq1_2 = cv.imread("./input/DataSeq1/yos_img_02.jpg",0)
DataSeq1_3 = cv.imread("./input/DataSeq1/yos_img_03.jpg",0)
red0a, red1a, red2a, red3a = reduce(DataSeq1_2)
red0b, red1b, red2b, red3b = reduce(DataSeq1_3)
U, V = opticalFlow(red2,red2a)
im_u = cv.applyColorMap(U.astype(np.uint8), cv.COLORMAP_JET)
im_v = cv.applyColorMap(V.astype(np.uint8), cv.COLORMAP_JET)
resultimage = warp(red2a,U,V)
imgs = itertools.cycle((red2,resultimage))
U, V = opticalFlow(red2a,red2b)
im_u1 = cv.applyColorMap(U.astype(np.uint8), cv.COLORMAP_JET)
im_v1 = cv.applyColorMap(V.astype(np.uint8), cv.COLORMAP_JET)
fig, axs = plt.subplots(2,2)
axs[0,0].set_title("Shift in X")
axs[0,0].set_ylabel("image 1 to image 2")
axs[1,0].set_ylabel("image 2 to image 3")
axs[0,0].imshow(im_u)
axs[1,0].imshow(im_u1)
axs[0,1].set_title("Shift in Y")
axs[0,1].imshow(im_v)
axs[1,1].imshow(im_v1)
plt.show()
resultimage1 = warp(red2b,U,V)
fig = plt.figure(2)
plt.subplot(121)
plt.subplot(121).set_xlabel("image 1 to 2")
plt.subplot(122).set_xlabel("image 2 to 3")
plt.title("Click on plot to cycle images")
imgs1 = itertools.cycle((red2a,resultimage1))
titles = itertools.cycle(("Original","warped"))
def onclick(event):
    plt.subplot(121).imshow(next(imgs),'gray')
    plt.subplot(122).imshow(next(imgs1),'gray')
    plt.title(next(titles))
    fig.canvas.draw()
cid = fig.canvas.mpl_connect('button_press_event', onclick)
plt.show()
fig, axs = plt.subplots(2,2)
axs[0,0].imshow(red2,cmap='gray')
axs[0,1].imshow(red2a,cmap='gray')
axs[1,0].imshow(resultimage,cmap='gray')
axs[1,1].imshow(resultimage1,cmap='gray')
axs[0,0].set_ylabel("Original Image")
axs[1,0].set_ylabel("Warped Image")
plt.show()

DataSeq2_1 = cv.imread("./input/DataSeq2/0.png",0)
DataSeq2_2 = cv.imread("./input/DataSeq2/1.png",0)
DataSeq2_3 = cv.imread("./input/DataSeq2/2.png",0)
red0, red1, red2, red3 = reduce(DataSeq2_1)
red0a, red1a, red2a, red3a = reduce(DataSeq2_2)
red0b, red1b, red2b, red3b = reduce(DataSeq2_3)
U, V = opticalFlow(red3,red3a)
im_u = cv.applyColorMap(U.astype(np.uint8), cv.COLORMAP_JET)
im_v = cv.applyColorMap(V.astype(np.uint8), cv.COLORMAP_JET)
resultimage = warp(red3a,U,V)
imgs = itertools.cycle((red3,resultimage))
U, V = opticalFlow(red3a,red3b)
im_u1 = cv.applyColorMap(U.astype(np.uint8), cv.COLORMAP_JET)
im_v1 = cv.applyColorMap(V.astype(np.uint8), cv.COLORMAP_JET)
fig, axs = plt.subplots(2,2)
axs[0,0].set_title("Shift in X")
axs[0,0].set_ylabel("image 1 to image 2")
axs[1,0].set_ylabel("image 2 to image 3")
axs[0,0].imshow(im_u)
axs[1,0].imshow(im_u1)
axs[0,1].set_title("Shift in Y")
axs[0,1].imshow(im_v)
axs[1,1].imshow(im_v1)
plt.show()
resultimage1 = warp(red3b,U,V)
fig = plt.figure(2)
plt.subplot(121)
plt.subplot(121).set_xlabel("image 1 to 2")
plt.subplot(122).set_xlabel("image 2 to 3")
plt.title("Click on plot to cycle images")
imgs1 = itertools.cycle((red3a,resultimage1))
titles = itertools.cycle(("Original","warped"))
def onclick(event):
    plt.subplot(121).imshow(next(imgs),'gray')
    plt.subplot(122).imshow(next(imgs1),'gray')
    plt.title(next(titles))
    fig.canvas.draw()
cid = fig.canvas.mpl_connect('button_press_event', onclick)
plt.show()
fig, axs = plt.subplots(2,2)
axs[0,0].imshow(red3,cmap='gray')
axs[0,1].imshow(red3a,cmap='gray')
axs[1,0].imshow(resultimage,cmap='gray')
axs[1,1].imshow(resultimage1,cmap='gray')
axs[0,0].set_ylabel("Original Image")
axs[1,0].set_ylabel("Warped Image")
plt.show()
shift0 = cv.imread("./input/TestSeq/Shift0.png",0)
shift10 = cv.imread("./input/TestSeq/ShiftR10.png",0)
shift20 = cv.imread("./input/TestSeq/ShiftR20.png",0)
shift40 = cv.imread("./input/TestSeq/ShiftR40.png",0)
Us10, Vs10 = HLK(shift0,shift10,4)
Us20, Vs20 = HLK(shift10,shift20,4)
Us40, Vs40 = HLK(shift20,shift40,5)
im_u10 = cv.applyColorMap(Us10.astype(np.uint8), cv.COLORMAP_JET)
im_v10 = cv.applyColorMap(Vs10.astype(np.uint8), cv.COLORMAP_JET)
im_u20 = cv.applyColorMap(Us20.astype(np.uint8), cv.COLORMAP_JET)
im_v20 = cv.applyColorMap(Vs20.astype(np.uint8), cv.COLORMAP_JET)
im_u40 = cv.applyColorMap(Us40.astype(np.uint8), cv.COLORMAP_JET)
im_v40 = cv.applyColorMap(Vs40.astype(np.uint8), cv.COLORMAP_JET)
fig, axs = plt.subplots(2,3)
axs[0,0].imshow(im_u10)
axs[0,1].imshow(im_u20)
axs[0,2].imshow(im_u40)
axs[1,0].imshow(im_v10)
axs[1,1].imshow(im_v20)
axs[1,2].imshow(im_v40)
axs[0,0].set_ylabel("Shift in X")
axs[1,0].set_ylabel("Shift in Y")
axs[0,0].set_title("Shift 10")
axs[0,1].set_title("Shift 20")
axs[0,2].set_title("Shift 40")
plt.show()
warped10 = warp(shift10,Us10,Vs10)
warped20 = warp(shift20,Us20+ Us10,Vs20+ Vs10)
warped40 = warp(shift40,Us40+Us20+ Us10,Vs40+Vs20+ Vs10)
fig, axs = plt.subplots(2,3)
axs[0,0].imshow(shift0,'gray')
axs[0,1].imshow(shift0,'gray')
axs[0,2].imshow(shift0,'gray')
axs[1,0].imshow(warped10,'gray')
axs[1,1].imshow(warped20,'gray')
axs[1,2].imshow(warped40,'gray')
axs[0,0].set_ylabel("Original")
axs[1,0].set_ylabel("Warped")
axs[0,0].set_title("Shift 10")
axs[0,1].set_title("Shift 20")
axs[0,2].set_title("Shift 40")
plt.show()
Uds10, Vds10 = HLK(DataSeq1_1,DataSeq1_2,4)
Uds20, Vds20 = HLK(DataSeq1_2,DataSeq1_3,4)
im_du10 = cv.applyColorMap(Uds10.astype(np.uint8), cv.COLORMAP_JET)
im_dv10 = cv.applyColorMap(Vds10.astype(np.uint8), cv.COLORMAP_JET)
im_du20 = cv.applyColorMap(Uds20.astype(np.uint8), cv.COLORMAP_JET)
im_dv20 = cv.applyColorMap(Vds20.astype(np.uint8), cv.COLORMAP_JET)
fig, axs = plt.subplots(2,2)
axs[0,0].imshow(im_du10)
axs[0,1].imshow(im_du20)
axs[1,0].imshow(im_dv10)
axs[1,1].imshow(im_dv20)
axs[0,0].set_ylabel("Shift in X")
axs[1,0].set_ylabel("Shift in Y")
axs[0,0].set_title("yos 1 to yos 2")
axs[0,1].set_title("yos 2 to yos 3")
plt.show()
warped1d1 = warp(DataSeq1_2,Uds10,Vds10)
warped2d1 = warp(DataSeq1_3,Uds20+ Uds10,Vds20+ Vds10)
fig, axs = plt.subplots(2,2)
axs[0,0].imshow(DataSeq1_1,'gray')
axs[0,1].imshow(DataSeq1_1,'gray')
axs[1,0].imshow(warped1d1,'gray')
axs[1,1].imshow(warped2d1,'gray')
axs[0,0].set_ylabel("Original")
axs[1,0].set_ylabel("Warped")
axs[0,0].set_title("yos 1 to yos 2")
axs[0,1].set_title("yos 1 to yos 3")
plt.show()
Uds10, Vds10 = HLK(DataSeq2_1,DataSeq2_2,4)
Uds20, Vds20 = HLK(DataSeq2_2,DataSeq2_3,4)
im_du10 = cv.applyColorMap(Uds10.astype(np.uint8), cv.COLORMAP_JET)
im_dv10 = cv.applyColorMap(Vds10.astype(np.uint8), cv.COLORMAP_JET)
im_du20 = cv.applyColorMap(Uds20.astype(np.uint8), cv.COLORMAP_JET)
im_dv20 = cv.applyColorMap(Vds20.astype(np.uint8), cv.COLORMAP_JET)
fig, axs = plt.subplots(2,2)
axs[0,0].imshow(im_du10)
axs[0,1].imshow(im_du20)
axs[1,0].imshow(im_dv10)
axs[1,1].imshow(im_dv20)
axs[0,0].set_ylabel("Shift in X")
axs[1,0].set_ylabel("Shift in Y")
axs[0,0].set_title("0 to 1")
axs[0,1].set_title("0 to 2")
plt.show()
warped1d1 = warp(DataSeq2_2,Uds10,Vds10)
warped2d1 = warp(DataSeq2_3,Uds20+ Uds10,Vds20+ Vds10)
fig, axs = plt.subplots(2,2)
axs[0,0].imshow(DataSeq2_1,'gray')
axs[0,1].imshow(DataSeq2_1,'gray')
axs[1,0].imshow(warped1d1,'gray')
axs[1,1].imshow(warped2d1,'gray')
axs[0,0].set_ylabel("Original")
axs[1,0].set_ylabel("Warped")
axs[0,0].set_title("0 to 1")
axs[0,1].set_title("0 to 2")
plt.show()